# Generated by Django 4.1.13 on 2024-07-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(default='No username provided', max_length=255)),
                ('profile_photo', models.CharField(default='No profile photo', max_length=255)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('firebase_metadata', models.JSONField(default=dict)),
            ],
        ),
    ]
