# Generated by Django 4.1.13 on 2024-07-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('height_feet', models.IntegerField()),
                ('height_inches', models.IntegerField()),
                ('weight', models.FloatField()),
                ('weight_unit', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Login.user')),
            ],
        ),
    ]
