# Generated by Django 4.1.13 on 2024-07-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
